import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    {
      type: 'category',
      label: '⌨️',
      collapsible: true,
      collapsed: false,
      items: [
        'aaru-65', 'aaru-tkl', 'ankh-numpad-r1',
        {
          type: 'link',
          label: 'Ankh Numpad R2',
          href: '/docs-ankh-r2/intro', // The external URL
        },
        {
          type: 'link',
          label: 'Elysium',
          href: '/docs-elysium/intro', // The external URL
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;